# test_server.py
import httpx

# --- Round 1 Test Payload ---
test_payload = {
    "email": "student@example.com",
    "secret": "Project-server", # Make sure this is your secret from .env
    "task": "final-build-test", # A brand new task ID
    "round": 1, # Set to 1 for the build test
    "nonce": "round-1-nonce-final",
    "brief": "Create a professional-looking webpage with a title that says 'Automated Deployment Test' and a paragraph explaining that this page was generated by an AI.",
    "checks": [],
    "evaluation_url": "https://example.com/notify",
    "attachments": []
}

try:
    print("--- 🚀 RUNNING ROUND 1 (BUILD) TEST ---")
    
    # This new line prints the secret the test script is sending
    print(f"--- 🔑 Sending SECRET: >>>{test_payload['secret']}<<< ---")
    
    response = httpx.post("http://127.0.0.1:8000/handle-task", json=test_payload)
    response.raise_for_status()
    
    print("✅ Success! Server responded with:")
    print(response.json())

except httpx.HTTPStatusError as e:
    print(f"❌ Error! Server responded with status {e.response.status_code}:")
    print(e.response.json())
except httpx.RequestError as e:
    print(f"❌ Request Error! Could not connect to the server: {e}")